# Generated by Django 3.0.5 on 2020-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_n', models.CharField(max_length=100)),
                ('customer_area', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('staff', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_n', models.CharField(max_length=100)),
                ('customer_area', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
