# Generated by Django 3.0.5 on 2020-04-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_req',
            name='outlet',
            field=models.CharField(default='room', max_length=100),
        ),
    ]
