# Generated by Django 3.0.5 on 2020-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_app_req_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='staff_id',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
