# Generated by Django 3.0.5 on 2020-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointments_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(default='vi', max_length=100),
        ),
    ]
