# Generated by Django 3.0.5 on 2020-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200410_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_n', models.CharField(max_length=100)),
                ('c_area', models.CharField(max_length=100)),
                ('tment', models.CharField(max_length=100)),
                ('time', models.CharField(default='vi', max_length=100)),
                ('s_id', models.CharField(default='no', max_length=100)),
            ],
        ),
    ]
