# Generated by Django 3.0.5 on 2020-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_req',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
